import type { Account, BudgetCategory, Transaction } from '@/lib/finance/types'

export const demoAccounts: Account[] = [
  { id: 'acc_checking', name: 'Main Checking', type: 'checking', balanceCents: 65_000_00 },
  { id: 'acc_credit', name: 'Credit Card', type: 'credit', balanceCents: 0 },
]

export const demoCategories: BudgetCategory[] = [
  { id: 'cat_rent', group: 'Housing & Utilities', name: 'Rent/Bond', limitCents: 13_600_00, spentCents: 0 },
  { id: 'cat_electricity', group: 'Housing & Utilities', name: 'Electricity', limitCents: 2_000_00, spentCents: 0 },
  { id: 'cat_water', group: 'Housing & Utilities', name: 'Water', limitCents: 1_000_00, spentCents: 0 },
  { id: 'cat_wifi', group: 'Housing & Utilities', name: 'Wi‑Fi/Internet', limitCents: 800_00, spentCents: 0 },

  { id: 'cat_cars', group: 'Vehicles & Transport', name: 'Cars', limitCents: 8_000_00, spentCents: 0 },
  { id: 'cat_transport', group: 'Vehicles & Transport', name: 'General Transport', limitCents: 3_000_00, spentCents: 0 },
  { id: 'cat_running', group: 'Vehicles & Transport', name: 'Vehicle Running Costs (Fuel/Tolls)', limitCents: 2_500_00, spentCents: 0 },

  { id: 'cat_groceries', group: 'Living & Services', name: 'Groceries (Burgundy/Loevenstein)', limitCents: 2_000_00, spentCents: 0 },
  { id: 'cat_domestic', group: 'Living & Services', name: 'Domestic Worker', limitCents: 1_360_00, spentCents: 0 },
  { id: 'cat_medical', group: 'Living & Services', name: 'Medical/Pharmacy', limitCents: 500_00, spentCents: 0 },
  { id: 'cat_insurance', group: 'Living & Services', name: 'Insurance', limitCents: 2_334_00, spentCents: 0 },
  { id: 'cat_subs', group: 'Living & Services', name: 'Subscriptions', limitCents: 700_00, spentCents: 0 },
  { id: 'cat_school', group: 'Living & Services', name: 'School Fees/Education', limitCents: 5_000_00, spentCents: 0 },

  { id: 'cat_savings', group: 'Savings/Investments', name: 'Savings/Investments', limitCents: 4_000_00, spentCents: 0 },

  { id: 'cat_wedding', group: 'Other', name: "Bryn's Wedding Fund", limitCents: 50_000_00, spentCents: 0 },

  { id: 'cat_security', group: 'Other', name: 'Security/Alarm', limitCents: 0, spentCents: 0 },
  { id: 'cat_gardening', group: 'Other', name: 'Gardening', limitCents: 0, spentCents: 0 },
  { id: 'cat_maintenance', group: 'Other', name: 'Maintenance/Repairs', limitCents: 0, spentCents: 0 },
  { id: 'cat_family_support', group: 'Other', name: 'Family Support/Allowances', limitCents: 0, spentCents: 0 },
  { id: 'cat_personal', group: 'Other', name: 'Personal Spending', limitCents: 0, spentCents: 0 },
  { id: 'cat_entertainment', group: 'Other', name: 'Entertainment & Dining Out', limitCents: 0, spentCents: 0 },
  { id: 'cat_clothing', group: 'Other', name: 'Clothing & Footwear', limitCents: 0, spentCents: 0 },
  { id: 'cat_debt', group: 'Other', name: 'Debt Repayments', limitCents: 0, spentCents: 0 },
  { id: 'cat_emergency', group: 'Other', name: 'Emergency Fund', limitCents: 0, spentCents: 0 },
  { id: 'cat_gifts', group: 'Other', name: 'Gifts & Donations', limitCents: 0, spentCents: 0 },
  { id: 'cat_pets', group: 'Other', name: 'Pet Care', limitCents: 0, spentCents: 0 },
]

export const demoTransactions: Transaction[] = [
  {
    id: 'txn_1',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_credit',
    categoryId: 'cat_groceries',
    amountCents: -1_210_00,
    merchant: 'Checkers',
    description: 'Groceries (weekly run)',
  },
  {
    id: 'txn_2',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_electricity',
    amountCents: -1_420_00,
    merchant: 'City Power',
    description: 'Electricity prepaid',
  },
  {
    id: 'txn_3',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_rent',
    amountCents: -13_600_00,
    merchant: 'Landlord',
    description: 'Rent/Bond',
  },
  {
    id: 'txn_4',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_water',
    amountCents: -620_00,
    merchant: 'Municipality',
    description: 'Water bill',
  },
  {
    id: 'txn_5',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_wifi',
    amountCents: -800_00,
    merchant: 'ISP',
    description: 'Internet subscription',
  },
  {
    id: 'txn_6',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_credit',
    categoryId: 'cat_transport',
    amountCents: -1_980_00,
    merchant: 'Uber',
    description: 'Transport',
  },
  {
    id: 'txn_7',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_running',
    amountCents: -2_120_00,
    merchant: 'Engen',
    description: 'Fuel & tolls',
  },
  {
    id: 'txn_8',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_domestic',
    amountCents: -1_360_00,
    merchant: 'Domestic Worker',
    description: 'Domestic worker payment',
  },
  {
    id: 'txn_9',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_insurance',
    amountCents: -2_334_00,
    merchant: 'Insurer',
    description: 'Insurance premium',
  },
  {
    id: 'txn_10',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_subs',
    amountCents: -522_00,
    merchant: 'Subscriptions',
    description: 'Monthly subscriptions',
  },
  {
    id: 'txn_11',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_school',
    amountCents: -5_000_00,
    merchant: 'School',
    description: 'School fees',
  },
  {
    id: 'txn_12',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_medical',
    amountCents: -180_00,
    merchant: 'Pharmacy',
    description: 'Medical',
  },
  {
    id: 'txn_13',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_savings',
    amountCents: -3_000_00,
    merchant: 'Savings',
    description: 'Transfer to savings/investments',
  },
  {
    id: 'txn_14',
    txnDate: new Date().toISOString().slice(0, 10),
    accountId: 'acc_checking',
    categoryId: 'cat_wedding',
    amountCents: -2_500_00,
    merchant: "Bryn's Wedding",
    description: 'Wedding fund payment (paid so far)',
  },
]

